In [43]:
import yfinance as yf
import ta
def get_price_data(stock_name,start='2018-01-01',end='2022-12-31'):
  stock = yf.Ticker(stock_name)
  history = stock.history(start= start,end = end)
  if history.empty:
    print("Check if entered stock name ",stock_name," is valid")
  else:
    indicators = ta.add_all_ta_features(history, open="Open",close="Close",high="High",low="Low",volume="Volume")
    return indicators

In [45]:
price_data = get_price_data("^DJI")
price_data.head()

/usr/local/lib/python3.10/dist-packages/ta/trend.py:780: RuntimeWarning: invalid value encountered in double_scalars
  dip[idx] = 100 * (self._dip[idx] / value)
/usr/local/lib/python3.10/dist-packages/ta/trend.py:785: RuntimeWarning: invalid value encountered in double_scalars
  din[idx] = 100 * (self._din[idx] / value)

,Open,High,Low,Close,Volume,Dividends,Stock Splits,volume_adi,volume_obv,volume_cmf,...,momentum_ppo,momentum_ppo_signal,momentum_ppo_hist,momentum_pvo,momentum_pvo_signal,momentum_pvo_hist,momentum_kama,others_dr,others_dlr,others_cr
Date,,,,,,,,,,,,,,,,,,,,,
2018-01-02 00:00:00-05:00,24809.349609,24864.189453,24741.699219,24824.009766,341130000,0.0,0.0,1.173326e+08,341130000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-14.558380,NaN,0.000000
2018-01-03 00:00:00-05:00,24850.449219,24941.919922,24825.550781,24922.679688,456790000,0.0,0.0,4.230732e+08,797920000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.397478,0.396690,0.397478
2018-01-04 00:00:00-05:00,24964.859375,25105.960938,24963.269531,25075.130859,403280000,0.0,0.0,6.520869e+08,1201200000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.611697,0.609833,1.011606
2018-01-05 00:00:00-05:00,25114.919922,25299.789062,25112.009766,25295.869141,358020000,0.0,0.0,9.951594e+08,1559220000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.880308,0.876455,1.900819
2018-01-08 00:00:00-05:00,25308.400391,25311.990234,25235.410156,25283.000000,341390000,0.0,0.0,1.078075e+09,1217830000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.050874,-0.050887,1.848977